// <auto-generated />
using Day01.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day01.Migrations
{
    [DbContext(typeof(Appcontext))]
    partial class AppcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day01.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptops & PCs"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("Day01.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Count = 10,
                            Description = "128GB, Natural Titanium",
                            Price = 999.99000000000001,
                            Title = "iPhone 15 Pro"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Count = 15,
                            Description = "256GB, Phantom Black",
                            Price = 799.99000000000001,
                            Title = "Samsung Galaxy S24"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Count = 5,
                            Description = "13-inch, 8GB RAM, 256GB SSD",
                            Price = 1099.0,
                            Title = "MacBook Air M3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Count = 8,
                            Description = "Intel Core i7, 16GB RAM",
                            Price = 1250.5,
                            Title = "Dell XPS 13"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Count = 20,
                            Description = "Wireless Noise Canceling Headphones",
                            Price = 349.99000000000001,
                            Title = "Sony WH-1000XM5"
                        });
                });

            modelBuilder.Entity("Day01.Models.Product", b =>
                {
                    b.HasOne("Day01.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Day01.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
